import argparse
import sys
from pathlib import Path
from dataclasses import dataclass
import numpy as np
from typing import List, Dict, Tuple
from ase.io import read
from ase import Atoms
from ase.io import write as ase_write
from pymatgen.core import Structure
from pymatgen.io.ase import AseAtomsAdaptor

# Import from common module using relative import
try:
    from ...common.mol_utils import (
        build_graph, split_molecules_pbc, unwrap_to_single_image, recenter_system, 
        wrap_to_box, deterministic_template_order, best_isomorphism
    )
except ImportError:
    # Fallback for direct script execution
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
    from common.mol_utils import (
        build_graph, split_molecules_pbc, unwrap_to_single_image, recenter_system, 
        wrap_to_box, deterministic_template_order, best_isomorphism
    )

def gro_box_line(cell: np.ndarray) -> str:
    """Return a GRO 9-field triclinic box line in nm. See CIF2GRO_USAGE.md for details."""
    # ASE cell is 3x3 with rows as cell vectors (Å). Convert to nm
    a, b, c = (cell[0] / 10.0, cell[1] / 10.0, cell[2] / 10.0)
    xx, xy, xz = a[0], a[1], a[2]
    yx, yy, yz = b[0], b[1], b[2]
    zx, zy, zz = c[0], c[1], c[2]
    return f"{xx:10.5f}{yy:10.5f}{zz:10.5f}{xy:10.5f}{xz:10.5f}{yx:10.5f}{yz:10.5f}{zx:10.5f}{zy:10.5f}"

def write_template_pdb(path: str, symbols: List[str], positions: np.ndarray, resname: str = "MOL"):
    """Write template molecule PDB with numbered atom names. See CIF2GRO_USAGE.md for details."""
    with open(path, "w") as f:
        f.write("REMARK   Template molecule with consistent atom ordering\n")
        for i, (sym, pos) in enumerate(zip(symbols, positions)):
            atom_id = i + 1
            aname = f"{sym}{atom_id}"
            x, y, z = pos
            # PDB ATOM record with numbered atom names
            line = f"ATOM  {atom_id:5d} {aname:<4s} {resname:3s}     1    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {sym:>2s}  \n"
            f.write(line)
        f.write("END\n")


def write_gro(path: str, atoms: Atoms, molecule_chunks: List[List[int]], per_mol_orders: Dict[int, List[int]], positions: List[np.ndarray], resid_name: str = "MOL"):
    """Write GRO with molecules concatenated; each molecule i is reordered by per_mol_orders[i]. See CIF2GRO_USAGE.md for details."""
    lines = []
    lines.append("Generated by cif2gro.py")
    n_tot = sum(len(ch) for ch in molecule_chunks)
    lines.append(f"{n_tot:5d}")

    atom_id = 1
    resid = 1
    symbols = atoms.get_chemical_symbols()
    for mi, idxs in enumerate(molecule_chunks):
        order_local = per_mol_orders[mi]
        assert len(order_local) == len(idxs)
        # Create simple atom names: element + running index within molecule
        local_to_global = {li: idxs[li] for li in range(len(idxs))}
        # Get positions for this molecule
        mol_pos = positions[mi]  # Already in Å
        for local_pos, local_idx in enumerate(order_local):
            gi = local_to_global[local_idx]
            sym = symbols[gi]
            aname = f"{sym}{local_pos+1}"
            resname = resid_name
            # GRO fixed-width line - use coordinates
            x, y, z = mol_pos[local_idx] / 10.0  # Å to nm
            line = f"{resid:5d}{resname:<5}{aname:>5}{atom_id:5d}{x:8.3f}{y:8.3f}{z:8.3f}"
            lines.append(line)
            atom_id += 1
        resid += 1
    lines.append(gro_box_line(np.array(atoms.cell)))

    with open(path, "w") as f:
        f.write("\n".join(lines) + ("" if lines[-1].endswith("\n") else "\n"))


# ----------------------------- main -----------------------------------
def main():
    ap = argparse.ArgumentParser(description="Convert CIF to GROMACS GRO with consistent per-molecule atom ordering")
    ap.add_argument("--cif", required=True, help="Input CIF file")
    ap.add_argument("--supercell", nargs=3, type=int, metavar=("NX","NY","NZ"), default=[1,1,1], help="Supercell repeats")
    ap.add_argument("--bond-scale", type=float, default=1.10, help="Covalent radii scale factor")
    ap.add_argument("--resname", type=str, default="MOL", help="Residue name in GRO")
    ap.add_argument("--out", default=None, help="Output GRO file (default: <cif_basename>.gro)")
    ap.add_argument("--no-recenter", action="store_true", help="Disable recentering (enabled by default)")
    ap.add_argument("--no-wrap", action="store_true", help="Disable wrapping (enabled by default)")
    args = ap.parse_args()
    
    # Generate default output filenames from input CIF basename
    cif_basename = Path(args.cif).stem  
    fout = f"{cif_basename}.gro"
    ftemp = f"{cif_basename}_template.pdb"
    args.recenter = not args.no_recenter
    args.wrap = not args.no_wrap

    try:
        atoms = read(args.cif)
        print(f"[INFO] Successfully loaded with ASE")
    except Exception as e1:
        print(f"[ERROR] Failed to read CIF with ASE: {e1}", file=sys.stderr)
        try:
            s = Structure.from_file(args.cif)
            atoms = AseAtomsAdaptor.get_atoms(s)
            print(f"[INFO] Loaded with pymatgen")
        except Exception as e2:
            print(f"[ERROR] Failed to read CIF with pymatgen: {e2}", file=sys.stderr)
            sys.exit(1)
        raise Exception("[ERROR] Could not load CIF file with either ASE or pymatgen")

    # Make supercell if needed
    nx, ny, nz = args.supercell
    if (nx, ny, nz) != (1,1,1):
        from ase.build import make_supercell
        S = np.diag([nx, ny, nz])
        atoms = make_supercell(atoms, S)

    # Identify molecules (connected components under PBC)
    comps = split_molecules_pbc(atoms, scale=args.bond_scale)
    if len(comps) == 1:
        print("[WARN] Detected a single connected component. This may not be a molecular crystal.")

    # Deterministic molecule ordering
    spos = atoms.get_scaled_positions()
    cell = atoms.get_cell()
    def frac_com(idxs):
        f = np.mean(spos[idxs], axis=0)
        return np.mod(f, 1.0)
    order_mols = sorted(range(len(comps)), key=lambda i: tuple(frac_com(comps[i])))
    comps = [comps[i] for i in order_mols]

    # Unwrap each molecule into one image and build a new Atoms in that geometry order
    unwrapped_positions = []
    all_numbers = atoms.numbers.copy()
    for idxs in comps:
        pos = unwrap_to_single_image(atoms, idxs)  # Å
        unwrapped_positions.append(pos)

    # Recenter system to form a compact cluster
    if args.recenter:
        print("[INFO] Recentering system to form a compact cluster...")
        unwrapped_positions = recenter_system(unwrapped_positions, np.array(atoms.get_cell()))

    # Wrap back into box
    if args.wrap:
        print("[INFO] Wrapping molecules back into the simulation box...")
        unwrapped_positions = wrap_to_box(unwrapped_positions, np.array(atoms.get_cell()))

    positions = unwrapped_positions
    # Build template order for molecule 0
    idxs0 = comps[0]
    mol0 = Atoms(numbers=all_numbers[idxs0], positions=positions[0])
    G0 = build_graph(mol0, scale=args.bond_scale)
    template_local_order = deterministic_template_order(G0, mol0, list(range(len(idxs0))))

    # Prepare per-molecule reorder maps (local -> desired local)
    per_mol_orders: Dict[int, List[int]] = {}
    per_mol_orders[0] = template_local_order

    # For other molecules: find isomorphism mapping to template and convert to template order
    for mi in range(1, len(comps)):
        idxs_i = comps[mi]
        mol_i = Atoms(numbers=all_numbers[idxs_i], positions=positions[mi])
        mapping = best_isomorphism(mol_i, mol0, list(range(len(idxs_i))), list(range(len(idxs0))), scale=args.bond_scale)
        # mapping: src_local -> ref_local ; we need to produce order of src locals that yields ref order template_local_order
        inv = {v:k for k,v in mapping.items()}  # ref_local -> src_local
        order_src_local = [inv[j] for j in template_local_order]
        per_mol_orders[mi] = order_src_local
    write_gro(fout, atoms, comps, per_mol_orders, positions, resid_name=args.resname)
    print(f"[OK] Wrote GRO with consistent per-molecule atom order: {fout}")

    # Write a single template molecule as PDB in the chosen order
    order0 = per_mol_orders[0]
    idxs_ordered = [idxs0[i] for i in order0]
    tpl_positions = positions[0][order0]
    tpl_symbols = [atoms.get_chemical_symbols()[idxs_ordered[i]] for i in range(len(order0))]
    write_template_pdb(ftemp, tpl_symbols, tpl_positions, resname=args.resname)
    print(f"[OK] Wrote template molecule PDB: {ftemp}")

if __name__ == "__main__":
    main()
