# QM/MM Settings Configuration File

# File paths
paths:
  sk_dir: "/home/takahashi/qmmm/sk/ob2/split"
  amber_prmtop: "../input/quinacridone_dmso.prmtop"
  pdbfile: "../input/quinacridone_dmso.pdb"
  qatoms: "../input/qmatoms"
  boxfile: "../input/quinacridone_dmso.box"

# Parallel settings
parallel:
  numcores_qm: 4
  numcores_mm: 4

# QM region settings
qm:
  charge: 0
  mult: 1

# DFTB parameters
dftb:
  slater_koster_files:
    C-C: "{sk_dir}/C-C.skf"
    C-H: "{sk_dir}/C-H.skf"
    H-C: "{sk_dir}/H-C.skf"
    H-H: "{sk_dir}/H-H.skf"
    C-N: "{sk_dir}/C-N.skf"
    N-C: "{sk_dir}/N-C.skf"
    N-N: "{sk_dir}/N-N.skf"
    N-H: "{sk_dir}/N-H.skf"
    H-N: "{sk_dir}/H-N.skf"
    C-O: "{sk_dir}/C-O.skf"
    O-C: "{sk_dir}/O-C.skf"
    O-O: "{sk_dir}/O-O.skf"
    N-O: "{sk_dir}/N-O.skf"
    O-N: "{sk_dir}/O-N.skf"
    H-O: "{sk_dir}/H-O.skf"
    O-H: "{sk_dir}/O-H.skf"
  third_order_full: true   
  hubbard_derivs:
      H: -0.1857
      C: -0.1492
      N: -0.1535
      O: -0.1575
  hcorrection_zeta: 4.0
  max_scc_iterations: 300  
  scc_log: true   
  energy_log: true               

# OpenMM settings
openmm:
  periodic: true
  periodic_nonbonded_cutoff: 9.0
  use_boxfile: true
  autoconstraints: HBonds  # for MD
  hydrogenmass: 1.0
  platform: "CPU"
