# MD Settings Configuration File

# MD parameters
md:
  timestep: 0.001          # ps (1.0 fs)
  traj_frequency: 50       # steps
  simulation_time: 200.0       # ps

# Output settings
output:
  directory: "output"
