# MD Settings Configuration File

# MD parameters
md:
  timestep: 0.001          # ps (1.0 fs)
  traj_frequency: 50       # steps
  nvt:
    temperature: 300.0       # K
    coupling_frequency: 1.0  # 1/ps
  simulation_time: 200.0       # ps
  special_wrapping: true  # Let ASH/mdtraj wrap coordinates each step
  special_wrapping_updatepos: true  # Push wrapped coordinates back to OpenMM 
  wrapping_atoms_file: "../input/qmatoms" 
 
# Output settings
output:
  directory: "output"
