#!/usr/bin/env python3
"""
Extract initial structure from mol1.dcd and save as XYZ for DFTB+.

Usage:
    python dcd2xyz.py
"""

import mdtraj as md
import numpy as np


def write_xyz(filename, topology, coordinates_nm):
    """Write XYZ file with simple element symbols (no atom type distinction).
    
    Parameters
    ----------
    filename : str
        Output XYZ file path.
    topology : md.Topology
        MDTraj topology object.
    coordinates_nm : np.ndarray
        Coordinates in nm (will be converted to Angstrom).
    """
    # Convert nm to Angstrom
    coords_ang = coordinates_nm * 10.0
    
    n_atoms = coords_ang.shape[0]
    
    with open(filename, 'w') as f:
        f.write(f"{n_atoms}\n")
        f.write("Generated by dcd2xyz.py\n")
        
        for i, atom in enumerate(topology.atoms):
            # Use element symbol only (C, H, N, etc.), not atom name (C1, H2, etc.)
            element = atom.element.symbol
            x, y, z = coords_ang[i]
            f.write(f"{element:2s} {x:15.8f} {y:15.8f} {z:15.8f}\n")


def main():
    # Input files
    trajectory = "mol1.dcd"
    topology = "mol1.pdb"
    
    # Output XYZ file
    output_xyz = "mol1.xyz"
    
    # Load trajectory
    print(f"Loading: {trajectory}")
    traj = md.load(trajectory, top=topology)
    print(f"  Frames: {traj.n_frames}")
    print(f"  Atoms: {traj.n_atoms}")
    
    # Extract first frame
    first_frame = traj[0]
    
    # Save as XYZ with simple element symbols
    write_xyz(output_xyz, first_frame.topology, first_frame.xyz[0])
    print(f"\nSaved initial structure: {output_xyz}")
    
    # Also print atom info
    print(f"\nAtoms in structure:")
    for atom in first_frame.topology.atoms:
        print(f"  {atom.index}: {atom.element.symbol} ({atom.name})")


if __name__ == "__main__":
    main()
