import argparse
import sys
from pathlib import Path
import numpy as np
from typing import List, Dict
from ase import Atoms
from ase.io import read, write as ase_write

# Import from same directory
from .mol_utils import (
    build_graph, split_molecules_pbc, unwrap_to_single_image, recenter_system, 
    wrap_to_box, deterministic_template_order, best_isomorphism, best_isomorphism_fast
)

def write_pdb_supercell(path: str, atoms: Atoms, molecule_chunks: List[List[int]], 
                       per_mol_orders: Dict[int, List[int]], 
                       unwrapped_positions: List[np.ndarray],
                       resname: str = "MOL"):
    """
    Write PDB file for the entire supercell with consistent atom ordering.
    """
    lines = []
    lines.append("TITLE     Generated by cif2pdb.py")
    lines.append("REMARK    Supercell with consistent per-molecule atom order")
    
    # Write CRYST1 record (box dimensions)
    cell = np.array(atoms.cell)
    a, b, c = np.linalg.norm(cell, axis=1)
    # Calculate angles (alpha, beta, gamma)
    alpha = np.degrees(np.arccos(np.dot(cell[1], cell[2]) / (b * c)))
    beta = np.degrees(np.arccos(np.dot(cell[0], cell[2]) / (a * c)))
    gamma = np.degrees(np.arccos(np.dot(cell[0], cell[1]) / (a * b)))
    
    lines.append(f"CRYST1{a:9.3f}{b:9.3f}{c:9.3f}{alpha:7.2f}{beta:7.2f}{gamma:7.2f} P 1           1")
    
    atom_id = 1
    symbols = atoms.get_chemical_symbols()
    
    for mi, idxs in enumerate(molecule_chunks):
        order_local = per_mol_orders[mi]
        local_to_global = {li: idxs[li] for li in range(len(idxs))}
        mol_unwrapped_pos = unwrapped_positions[mi]
        
        for local_pos, local_idx in enumerate(order_local):
            gi = local_to_global[local_idx]
            sym = symbols[gi]
            element = sym[0] if len(sym) <= 2 else sym[:2]
            aname = f"{sym}{local_pos+1}"
            
            # Get coordinates
            x, y, z = mol_unwrapped_pos[local_idx]
            
            # PDB ATOM record
            # ATOM serial name altLoc resName chainID resSeq iCode x y z occupancy tempFactor element charge
            line = f"ATOM  {atom_id:5d} {aname:<4s} {resname:3s} A{mi+1:4d}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {element:>2s}  "
            lines.append(line)
            atom_id += 1
        
        lines.append("TER")
    
    lines.append("END")
    
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def cell_to_box_vectors(a, b, c, alpha, beta, gamma):
    """
    Convert cell parameters to box vectors for triclinic cells.
    
    Args:
        a, b, c: Cell lengths in Angstrom
        alpha, beta, gamma: Cell angles in degrees
    
    Returns:
        numpy.ndarray: 3x3 box vectors [[ax, ay, az], [bx, by, bz], [cx, cy, cz]]
    """
    # Convert angles to radians
    alpha_rad = np.radians(alpha)
    beta_rad = np.radians(beta)
    gamma_rad = np.radians(gamma)
    
    # Box vector a along x-axis
    ax, ay, az = a, 0.0, 0.0
    
    # Box vector b in xy-plane
    bx = b * np.cos(gamma_rad)
    by = b * np.sin(gamma_rad)
    bz = 0.0
    
    # Box vector c
    cx = c * np.cos(beta_rad)
    cy = c * (np.cos(alpha_rad) - np.cos(beta_rad) * np.cos(gamma_rad)) / np.sin(gamma_rad)
    cz = np.sqrt(c**2 - cx**2 - cy**2)
    
    return np.array([[ax, ay, az], [bx, by, bz], [cx, cy, cz]])


def write_box_file(path: str, atoms: Atoms):
    """
    Write PBC box vectors to a file for triclinic cells.
    
    Format: 3x3 matrix (each row is a box vector in Angstrom)
    Also includes cell parameters as comments for reference.
    
    Args:
        path: Output file path
        atoms: ASE Atoms object with cell information
    """
    cell = np.array(atoms.cell)
    a, b, c = np.linalg.norm(cell, axis=1)
    # Calculate angles (alpha, beta, gamma) in degrees
    alpha = np.degrees(np.arccos(np.dot(cell[1], cell[2]) / (b * c)))
    beta = np.degrees(np.arccos(np.dot(cell[0], cell[2]) / (a * c)))
    gamma = np.degrees(np.arccos(np.dot(cell[0], cell[1]) / (a * b)))
    
    # Calculate box vectors
    box_vectors = cell_to_box_vectors(a, b, c, alpha, beta, gamma)
    
    with open(path, "w") as f:
        f.write(f"# PBC Box vectors (3x3 matrix, each row is a vector in Angstrom)\n")
        f.write(f"# Cell parameters: a={a:.6f} b={b:.6f} c={c:.6f} alpha={alpha:.4f} beta={beta:.4f} gamma={gamma:.4f}\n")
        for vec in box_vectors:
            f.write(f"{vec[0]:.10f} {vec[1]:.10f} {vec[2]:.10f}\n")


def write_crd_supercell(path: str, atoms: Atoms, molecule_chunks: List[List[int]], 
                       per_mol_orders: Dict[int, List[int]], 
                       unwrapped_positions: List[np.ndarray],
                       resname: str = "MOL"):
    """
    Write CHARMM CRD file for the entire supercell with consistent atom ordering.
    """
    lines = []
    lines.append("* Generated by cif2pdb.py")
    lines.append("* Supercell with consistent per-molecule atom order")
    lines.append("*")
    
    # Count total atoms
    n_atoms = sum(len(ch) for ch in molecule_chunks)
    lines.append(f"{n_atoms:10d}  EXT")
    
    atom_id = 1
    symbols = atoms.get_chemical_symbols()
    
    for mi, idxs in enumerate(molecule_chunks):
        order_local = per_mol_orders[mi]
        local_to_global = {li: idxs[li] for li in range(len(idxs))}
        mol_unwrapped_pos = unwrapped_positions[mi]
        
        for local_pos, local_idx in enumerate(order_local):
            gi = local_to_global[local_idx]
            sym = symbols[gi]
            aname = f"{sym}{local_pos+1}"
            
            # Get coordinates
            x, y, z = mol_unwrapped_pos[local_idx]
            
            # CHARMM CRD extended format (EXT):
            # Fixed-width format - each field must be exact width
            # Cols 1-10: atom number (I10)
            # Cols 11-20: residue number (I10)  
            # Cols 21-30: residue name (A10, usually 2 spaces + name left-justified in 8 chars)
            # Cols 31-40: atom name (A10, usually 2 spaces + name left-justified in 8 chars)
            # Cols 41-60: X (F20.10 or can be narrower)
            # Cols 61-80: Y (F20.10)
            # Cols 81-100: Z (F20.10)
            # Cols 101-110: segment ID (A10, usually 2 spaces + ID in 8 chars)
            # Cols 111-120: residue ID (I10)
            # Cols 121-130: weighting (F10.5 or similar)
            
            resid = mi + 1
            segid = "SYS"
            weighting = 0.0
            
            # Use exact field widths
            line = (f"{atom_id:10d}"           # cols 1-10
                   f"{resid:10d}"              # cols 11-20
                   f"  {resname:<8s}"          # cols 21-30 (2 spaces + 8-char field)
                   f"  {aname:<8s}"            # cols 31-40 (2 spaces + 8-char field)
                   f"{x:20.10f}"               # cols 41-60
                   f"{y:20.10f}"               # cols 61-80
                   f"{z:20.10f}"               # cols 81-100
                   f"  {segid:<8s}"            # cols 101-110 (2 spaces + 8-char field)
                   f"{resid:10d}"              # cols 111-120
                   f"{weighting:10.5f}")       # cols 121-130
            
            lines.append(line)
            atom_id += 1
    
    # Add crystal/box information if present
    # CHARMM extended CRD format supports crystal parameters at the end
    cell = atoms.get_cell()
    if cell is not None and not np.allclose(cell.lengths(), 0):
        a, b, c = cell.lengths()
        # Calculate angles (alpha, beta, gamma) in degrees
        alpha = np.degrees(np.arccos(np.dot(cell[1], cell[2]) / (b * c)))
        beta = np.degrees(np.arccos(np.dot(cell[0], cell[2]) / (a * c)))
        gamma = np.degrees(np.arccos(np.dot(cell[0], cell[1]) / (a * b)))
        
        # Write crystal dimensions (format used by CHARMM)
        lines.append(f"{a:20.10f}{b:20.10f}{c:20.10f}{alpha:20.10f}{beta:20.10f}{gamma:20.10f}")
    
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def infer_sybyl_atom_type(element: str, degree: int, num_h_neighbors: int) -> str:
    """
    Infer SYBYL atom type from element and connectivity.
    """
    # Common SYBYL atom types for organic molecules
    if element == 'C':
        if degree == 4:
            return 'C.3'    # sp3 carbon
        elif degree == 3:
            return 'C.ar'   # aromatic carbon (assuming aromatic for degree 3)
        elif degree == 2:
            return 'C.2'    # sp2 carbon
        elif degree == 1:
            return 'C.1'    # sp carbon
        else:
            return 'C.3'    # default
    elif element == 'H':
        return 'H'
    elif element == 'N':
        if degree == 3:
            return 'N.3'    # sp3 nitrogen
        elif degree == 2:
            return 'N.2'    # sp2 nitrogen
        elif degree == 1:
            return 'N.1'    # sp nitrogen
        else:
            return 'N.3'
    elif element == 'O':
        if degree == 2:
            return 'O.3'    # sp3 oxygen (ether, alcohol)
        elif degree == 1:
            return 'O.2'    # sp2 oxygen (carbonyl)
        else:
            return 'O.3'
    elif element == 'S':
        if degree == 2:
            return 'S.3'    # sp3 sulfur
        elif degree == 1:
            return 'S.2'    # sp2 sulfur
        else:
            return 'S.3'
    elif element == 'P':
        return 'P.3'
    elif element == 'F':
        return 'F'
    elif element == 'Cl':
        return 'Cl'
    elif element == 'Br':
        return 'Br'
    elif element == 'I':
        return 'I'
    else:
        # For unknown elements, return the element symbol
        return element


def write_mol2_single_molecule(path: str, atoms: Atoms, mol_indices: List[int],
                               ordered_indices: List[int], unwrapped_pos: np.ndarray,
                               bond_scale: float = 1.10, mol_name: str = "MOL"):
    """
    Write SYBYL-compliant mol2 file for a single molecule with bond information.
    """
    # Reorder positions and get element symbols
    symbols = atoms.get_chemical_symbols()
    mol_symbols = [symbols[mol_indices[i]] for i in ordered_indices]
    mol_positions = unwrapped_pos[ordered_indices]
    
    # Build graph to get bonds
    mol_atoms = Atoms(numbers=[atoms.numbers[mol_indices[i]] for i in ordered_indices],
                     positions=mol_positions)
    G = build_graph(mol_atoms, scale=bond_scale)
    
    # Infer SYBYL atom types
    sybyl_types = []
    for i, sym in enumerate(mol_symbols):
        degree = G.degree[i]
        num_h = sum(1 for j in G.neighbors(i) if mol_symbols[j] == 'H')
        sybyl_type = infer_sybyl_atom_type(sym, degree, num_h)
        sybyl_types.append(sybyl_type)
    
    # Write mol2 file in SYBYL format
    lines = []
    lines.append("@<TRIPOS>MOLECULE")
    lines.append(mol_name)
    lines.append(f" {len(mol_symbols)} {G.number_of_edges()} 1 0 0")
    lines.append("SMALL")
    lines.append("USER_CHARGES")
    lines.append("")
    lines.append("")
    
    lines.append("@<TRIPOS>ATOM")
    for i, (sym, pos, sybyl_type) in enumerate(zip(mol_symbols, mol_positions, sybyl_types)):
        atom_id = i + 1
        atom_name = f"{sym}{atom_id}"
        x, y, z = pos
        # SYBYL mol2 format: atom_id atom_name x y z atom_type [subst_id [subst_name [charge [status_bit]]]]
        lines.append(f"{atom_id:7d} {atom_name:<8s}{x:10.4f}{y:10.4f}{z:10.4f} {sybyl_type:<8s}    1 {mol_name:<8s}    0.0000")
    
    lines.append("@<TRIPOS>BOND")
    bond_id = 1
    for edge in sorted(G.edges()):
        i, j = edge
        # Determine bond type (1=single, 2=double, 3=triple, ar=aromatic)
        # For now, use 'ar' for aromatic carbons, '1' otherwise
        if sybyl_types[i] == 'C.ar' and sybyl_types[j] == 'C.ar':
            bond_type = 'ar'
        else:
            bond_type = '1'
        # mol2 uses 1-based indexing
        lines.append(f"{bond_id:6d}{i+1:5d}{j+1:5d}     {bond_type}")
        bond_id += 1
    
    lines.append("@<TRIPOS>SUBSTRUCTURE")
    lines.append(f"     1 {mol_name:<8s}        1 TEMP              0 ****  ****    0 ROOT")
    
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def cif_to_pdb(cif_file: str, output_pdb: str = None, output_mol2: str = None,
               output_box: str = None,
               supercell: tuple = (1, 1, 1), bond_scale: float = 1.10,
               resname: str = "MOL", mol_name: str = "MOL",
               recenter: bool = True, wrap: bool = True):
    """
    Convert CIF file to PDB supercell and mol2 template for GAFF2/AMBER.
    
    Args:
        cif_file: Input CIF file path
        output_pdb: Output PDB file path (default: {basename}.pdb)
        output_mol2: Output mol2 file path (default: {basename}_template.mol2)
        output_box: Output box file path (default: {basename}.box)
        supercell: Supercell dimensions (nx, ny, nz)
        bond_scale: Covalent radii scale factor for bond detection
        resname: Residue name in PDB
        mol_name: Molecule name for mol2
        recenter: Recenter system to form compact cluster
        wrap: Wrap molecules back into simulation box
    
    Returns:
        dict with 'pdb', 'mol2', 'box', 'n_atoms', 'n_molecules' keys
    """
    from pymatgen.core import Structure
    from pymatgen.io.ase import AseAtomsAdaptor
    
    cif_path = Path(cif_file)
    cif_basename = cif_path.stem
    
    if output_pdb is None:
        output_pdb = str(cif_path.parent / f"{cif_basename}.pdb")
    if output_mol2 is None:
        output_mol2 = str(cif_path.parent / f"{cif_basename}_template.mol2")
    if output_box is None:
        output_box = str(cif_path.parent / f"{cif_basename}.box")
    
    # Load CIF file
    try:
        atoms = read(cif_file)
        print(f"[INFO] Successfully loaded with ASE")
    except Exception as e1:
        print(f"[WARN] Failed to read CIF with ASE: {e1}")
        try:
            s = Structure.from_file(cif_file)
            atoms = AseAtomsAdaptor.get_atoms(s)
            print(f"[INFO] Loaded with pymatgen")
        except Exception as e2:
            raise Exception(f"[ERROR] Could not load CIF file: {e2}")
    
    # Make supercell if needed
    nx, ny, nz = supercell
    if (nx, ny, nz) != (1, 1, 1):
        from ase.build import make_supercell
        S = np.diag([nx, ny, nz])
        atoms = make_supercell(atoms, S)
        print(f"[INFO] Created {nx}x{ny}x{nz} supercell: {len(atoms)} atoms")
    
    # Identify molecules
    comps = split_molecules_pbc(atoms, scale=bond_scale)
    print(f"[INFO] Detected {len(comps)} molecules")
    
    if len(comps) == 1:
        print("[WARN] Detected a single connected component. This may not be a molecular crystal.")
    
    # Deterministic molecule ordering by fractional COM
    spos = atoms.get_scaled_positions()
    def frac_com(idxs):
        f = np.mean(spos[idxs], axis=0)
        return np.mod(f, 1.0)
    order_mols = sorted(range(len(comps)), key=lambda i: tuple(frac_com(comps[i])))
    comps = [comps[i] for i in order_mols]
    
    # Unwrap each molecule
    unwrapped_positions = []
    all_numbers = atoms.numbers.copy()
    for idxs in comps:
        pos = unwrap_to_single_image(atoms, idxs)
        unwrapped_positions.append(pos)
    
    # Optional: Recenter and wrap
    if recenter:
        print("[INFO] Recentering system to form a compact cluster...")
        unwrapped_positions = recenter_system(unwrapped_positions, np.array(atoms.get_cell()))
    
    if wrap:
        print("[INFO] Wrapping molecules back into the simulation box...")
        unwrapped_positions = wrap_to_box(unwrapped_positions, np.array(atoms.get_cell()))
    
    # Build template order for molecule 0
    idxs0 = comps[0]
    mol0 = Atoms(numbers=all_numbers[idxs0], positions=unwrapped_positions[0])
    G0 = build_graph(mol0, scale=bond_scale)
    template_local_order = deterministic_template_order(G0, mol0, list(range(len(idxs0))))
    print(f"[INFO] Template molecule has {len(idxs0)} atoms")
    
    # Prepare per-molecule reorder maps
    per_mol_orders: Dict[int, List[int]] = {}
    per_mol_orders[0] = template_local_order
    # For other molecules: find isomorphism mapping to template
    for mi in range(1, len(comps)):
        idxs_i = comps[mi]
        mol_i = Atoms(numbers=all_numbers[idxs_i], positions=unwrapped_positions[mi])
        mapping = best_isomorphism(mol_i, mol0, list(range(len(idxs_i))),
                                   list(range(len(idxs0))), scale=bond_scale)
        inv = {v: k for k, v in mapping.items()}
        order_src_local = [inv[j] for j in template_local_order]
        per_mol_orders[mi] = order_src_local
    
    # Write PDB supercell
    write_pdb_supercell(output_pdb, atoms, comps, per_mol_orders, unwrapped_positions, resname=resname)
    print(f"[OK] Wrote supercell PDB: {output_pdb}")
    
    # Write mol2 for template molecule (for GAFF2)
    write_mol2_single_molecule(output_mol2, atoms, idxs0, template_local_order,
                               unwrapped_positions[0], bond_scale=bond_scale,
                               mol_name=mol_name)
    print(f"[OK] Wrote template molecule mol2: {output_mol2}")
    print(f"[INFO] Use this mol2 file with antechamber/parmchk2 for GAFF2 parameterization")
    
    # Write box parameters file
    write_box_file(output_box, atoms)
    print(f"[OK] Wrote box parameters: {output_box}")
    
    return {
        'pdb': output_pdb,
        'mol2': output_mol2,
        'box': output_box,
        'n_atoms': len(atoms),
        'n_molecules': len(comps)
    }


def cif_to_pdb_wlhash(cif_file: str, output_pdb: str = None, output_mol2: str = None, 
                      output_box: str = None, supercell: tuple = (1, 1, 1),
                      bond_scale: float = 1.10, resname: str = "MOL", 
                      mol_name: str = "MOL", recenter: bool = True, wrap: bool = True):
    """
    Fast AND accurate version using Weisfeiler-Lehman graph hashing.
    
    Uses WL hash to identify chemically equivalent atoms, then matches
    by coordinate distance. O(n log n) instead of O(n!) complexity.
    
    Recommended for:
    - Large molecules (>50 atoms/molecule)
    - Large supercells (>20 molecules)
    - Production use with force field parameterization
    
    Algorithm:
    1. Build molecular graph and compute WL hash for each atom
    2. Atoms with same hash are chemically equivalent
    3. Match by nearest distance after Kabsch alignment
    """
    from pymatgen.core import Structure
    from pymatgen.io.ase import AseAtomsAdaptor
    
    cif_path = Path(cif_file)
    cif_basename = cif_path.stem
    
    if output_pdb is None:
        output_pdb = str(cif_path.parent / f"{cif_basename}.pdb")
    if output_mol2 is None:
        output_mol2 = str(cif_path.parent / f"{cif_basename}_template.mol2")
    if output_box is None:
        output_box = str(cif_path.parent / f"{cif_basename}.box")
    
    # Load CIF file
    try:
        atoms = read(cif_file)
        print(f"[INFO] Successfully loaded with ASE")
    except Exception as e1:
        print(f"[WARN] Failed to read CIF with ASE: {e1}")
        try:
            s = Structure.from_file(cif_file)
            atoms = AseAtomsAdaptor.get_atoms(s)
            print(f"[INFO] Loaded with pymatgen")
        except Exception as e2:
            raise Exception(f"[ERROR] Could not load CIF file: {e2}")
    
    # Make supercell if needed
    nx, ny, nz = supercell
    if (nx, ny, nz) != (1, 1, 1):
        from ase.build import make_supercell
        S = np.diag([nx, ny, nz])
        atoms = make_supercell(atoms, S)
        print(f"[INFO] Created {nx}x{ny}x{nz} supercell: {len(atoms)} atoms")
    
    # Identify molecules
    comps = split_molecules_pbc(atoms, scale=bond_scale)
    print(f"[INFO] Detected {len(comps)} molecules")
    
    if len(comps) == 1:
        print("[WARN] Detected a single connected component. This may not be a molecular crystal.")
    
    # Deterministic molecule ordering by fractional COM
    spos = atoms.get_scaled_positions()
    def frac_com(idxs):
        f = np.mean(spos[idxs], axis=0)
        return np.mod(f, 1.0)
    order_mols = sorted(range(len(comps)), key=lambda i: tuple(frac_com(comps[i])))
    comps = [comps[i] for i in order_mols]
    
    # Unwrap each molecule
    unwrapped_positions = []
    all_numbers = atoms.numbers.copy()
    for idxs in comps:
        pos = unwrap_to_single_image(atoms, idxs)
        unwrapped_positions.append(pos)
    
    # Optional: Recenter and wrap
    if recenter:
        print("[INFO] Recentering system to form a compact cluster...")
        unwrapped_positions = recenter_system(unwrapped_positions, np.array(atoms.get_cell()))
    
    if wrap:
        print("[INFO] Wrapping molecules back into the simulation box...")
        unwrapped_positions = wrap_to_box(unwrapped_positions, np.array(atoms.get_cell()))
    
    # Build template order for molecule 0
    idxs0 = comps[0]
    mol0 = Atoms(numbers=all_numbers[idxs0], positions=unwrapped_positions[0])
    G0 = build_graph(mol0, scale=bond_scale)
    template_local_order = deterministic_template_order(G0, mol0, list(range(len(idxs0))))
    print(f"[INFO] Template molecule has {len(idxs0)} atoms")
    
    # Prepare per-molecule reorder maps using FAST isomorphism
    per_mol_orders: Dict[int, List[int]] = {}
    per_mol_orders[0] = template_local_order
    
    print(f"[INFO] Using WL-hash based fast accurate matching...")
    # For other molecules: find isomorphism mapping to template
    for mi in range(1, len(comps)):
        idxs_i = comps[mi]
        mol_i = Atoms(numbers=all_numbers[idxs_i], positions=unwrapped_positions[mi])
        # Use fast isomorphism with WL hashing
        mapping = best_isomorphism_fast(mol_i, mol0, list(range(len(idxs_i))),
                                        list(range(len(idxs0))), scale=bond_scale)
        inv = {v: k for k, v in mapping.items()}
        order_src_local = [inv[j] for j in template_local_order]
        per_mol_orders[mi] = order_src_local
        
        if (mi + 1) % 10 == 0:
            print(f"[INFO] Processed {mi + 1}/{len(comps)} molecules...")
    
    # Write PDB supercell
    write_pdb_supercell(output_pdb, atoms, comps, per_mol_orders, unwrapped_positions, resname=resname)
    print(f"[OK] Wrote supercell PDB: {output_pdb}")
    
    # Write mol2 for template molecule (for GAFF2)
    write_mol2_single_molecule(output_mol2, atoms, idxs0, template_local_order,
                               unwrapped_positions[0], bond_scale=bond_scale,
                               mol_name=mol_name)
    print(f"[OK] Wrote template molecule mol2: {output_mol2}")
    print(f"[INFO] Use this mol2 file with antechamber/parmchk2 for GAFF2 parameterization")
    
    # Write box parameters file
    write_box_file(output_box, atoms)
    print(f"[OK] Wrote box parameters: {output_box}")
    
    return {
        'pdb': output_pdb,
        'mol2': output_mol2,
        'box': output_box,
        'n_atoms': len(atoms),
        'n_molecules': len(comps)
    }


def cif_to_pdb_coordsort(cif_file: str, output_pdb: str = None, output_mol2: str = None, 
                         output_box: str = None, supercell: tuple = (1, 1, 1),
                         bond_scale: float = 1.10, resname: str = "MOL", 
                         mol_name: str = "MOL", recenter: bool = True, wrap: bool = True):
    """
    Fast version using coordinate sorting (no graph matching).
    
    Uses simple atom sorting (by atomic number, then coordinates) instead of
    best_isomorphism for matching molecules. Much faster for large systems,
    but atom ordering may be less consistent across molecules.
    
    Suitable for:
    - Large supercells (e.g., >100 molecules)
    - Systems with large molecules (e.g., >100 atoms/molecule)
    - Quick visualization/testing
    
    Not recommended for:
    - Systems requiring exact atom ordering consistency (e.g., force field parameterization)
    """
    from pymatgen.core import Structure
    from pymatgen.io.ase import AseAtomsAdaptor
    
    cif_path = Path(cif_file)
    cif_basename = cif_path.stem
    
    if output_pdb is None:
        output_pdb = str(cif_path.parent / f"{cif_basename}.pdb")
    if output_mol2 is None:
        output_mol2 = str(cif_path.parent / f"{cif_basename}_template.mol2")
    if output_box is None:
        output_box = str(cif_path.parent / f"{cif_basename}.box")
    
    # Load CIF file
    try:
        atoms = read(cif_file)
        print(f"[INFO] Successfully loaded with ASE")
    except Exception as e1:
        print(f"[WARN] Failed to read CIF with ASE: {e1}")
        try:
            s = Structure.from_file(cif_file)
            atoms = AseAtomsAdaptor.get_atoms(s)
            print(f"[INFO] Loaded with pymatgen")
        except Exception as e2:
            raise Exception(f"[ERROR] Could not load CIF file: {e2}")
    
    # Make supercell if needed
    nx, ny, nz = supercell
    if (nx, ny, nz) != (1, 1, 1):
        from ase.build import make_supercell
        S = np.diag([nx, ny, nz])
        atoms = make_supercell(atoms, S)
        print(f"[INFO] Created {nx}x{ny}x{nz} supercell: {len(atoms)} atoms")
    
    # Identify molecules
    comps = split_molecules_pbc(atoms, scale=bond_scale)
    print(f"[INFO] Detected {len(comps)} molecules")
    
    if len(comps) == 1:
        print("[WARN] Detected a single connected component. This may not be a molecular crystal.")
    
    # Deterministic molecule ordering by fractional COM
    spos = atoms.get_scaled_positions()
    def frac_com(idxs):
        f = np.mean(spos[idxs], axis=0)
        return np.mod(f, 1.0)
    order_mols = sorted(range(len(comps)), key=lambda i: tuple(frac_com(comps[i])))
    comps = [comps[i] for i in order_mols]
    
    # Unwrap each molecule
    unwrapped_positions = []
    all_numbers = atoms.numbers.copy()
    for idxs in comps:
        pos = unwrap_to_single_image(atoms, idxs)
        unwrapped_positions.append(pos)
    
    # Optional: Recenter and wrap
    if recenter:
        print("[INFO] Recentering system to form a compact cluster...")
        unwrapped_positions = recenter_system(unwrapped_positions, np.array(atoms.get_cell()))
    
    if wrap:
        print("[INFO] Wrapping molecules back into the simulation box...")
        unwrapped_positions = wrap_to_box(unwrapped_positions, np.array(atoms.get_cell()))
    
    # Build template order for molecule 0
    idxs0 = comps[0]
    mol0 = Atoms(numbers=all_numbers[idxs0], positions=unwrapped_positions[0])
    G0 = build_graph(mol0, scale=bond_scale)
    template_local_order = deterministic_template_order(G0, mol0, list(range(len(idxs0))))
    print(f"[INFO] Template molecule has {len(idxs0)} atoms")
    
    # Fast matching: sort atoms by (atomic_number, then distance from centroid)
    def fast_atom_order(numbers, positions):
        """Sort atoms by atomic number, then by distance from centroid (canonical order)."""
        centroid = positions.mean(axis=0)
        dists = np.linalg.norm(positions - centroid, axis=1)
        # Create sorting key: (atomic_number, distance)
        order = np.lexsort((dists, numbers))
        return order
    
    per_mol_orders: Dict[int, List[int]] = {}
    per_mol_orders[0] = template_local_order
    
    print(f"[INFO] Using fast atom matching (no graph isomorphism)...")
    
    # For all other molecules, use same ordering strategy as template
    # Sort by (atomic_number, distance from centroid), then map to template order
    template_numbers = all_numbers[idxs0]
    template_sort_order = fast_atom_order(template_numbers, unwrapped_positions[0])
    # template_local_order[i] is the i-th atom to output
    # We need to map: for each molecule, find equivalent sorting and remap
    
    for mi in range(1, len(comps)):
        idxs_i = comps[mi]
        mol_numbers = all_numbers[idxs_i]
        mol_sort_order = fast_atom_order(mol_numbers, unwrapped_positions[mi])
        
        # Create mapping: sorted position -> local index
        # template_sort_order[k] = local index of k-th atom in sorted order (template)
        # mol_sort_order[k] = local index of k-th atom in sorted order (this mol)
        # template_local_order[j] = which local index is j-th in output
        
        # For template: output order is template_local_order
        # We want to find: for each position j in template_local_order,
        # which atom in mol_i corresponds?
        
        # Build inverse: template_inv[local_idx] = position in sorted order
        template_inv = np.argsort(template_sort_order)
        mol_inv = np.argsort(mol_sort_order)
        
        # Map template_local_order to mol order
        order_local = []
        for j in range(len(idxs_i)):
            tpl_local = template_local_order[j]  # template's j-th output atom (local idx)
            sorted_pos = template_inv[tpl_local]  # position in sorted order
            mol_local = mol_sort_order[sorted_pos]  # mol's atom at same sorted position
            order_local.append(int(mol_local))
        
        per_mol_orders[mi] = order_local
    
    # Write PDB supercell
    write_pdb_supercell(output_pdb, atoms, comps, per_mol_orders, unwrapped_positions, resname=resname)
    print(f"[OK] Wrote supercell PDB: {output_pdb}")
    
    # Write mol2 for template molecule (for GAFF2)
    write_mol2_single_molecule(output_mol2, atoms, idxs0, template_local_order,
                               unwrapped_positions[0], bond_scale=bond_scale,
                               mol_name=mol_name)
    print(f"[OK] Wrote template molecule mol2: {output_mol2}")
    print(f"[INFO] Use this mol2 file with antechamber/parmchk2 for GAFF2 parameterization")
    
    # Write box parameters file
    write_box_file(output_box, atoms)
    print(f"[OK] Wrote box parameters: {output_box}")
    
    return {
        'pdb': output_pdb,
        'mol2': output_mol2,
        'box': output_box,
        'n_atoms': len(atoms),
        'n_molecules': len(comps)
    }


def main():
    ap = argparse.ArgumentParser(description="Create supercell PDB and single-molecule mol2 from CIF for GAFF2/AMBER.")
    ap.add_argument("--cif", required=True, help="Input CIF file")
    ap.add_argument("--supercell", nargs=3, type=int, metavar=("NX","NY","NZ"), default=[1,1,1], help="Supercell repeats")
    ap.add_argument("--bond-scale", type=float, default=1.10, help="Covalent radii scale factor")
    ap.add_argument("--resname", type=str, default="MOL", help="Residue name in PDB")
    ap.add_argument("--mol-name", type=str, default="MOL", help="Molecule name for mol2")
    ap.add_argument("--no-recenter", action="store_true", help="Disable recentering (enabled by default)")
    ap.add_argument("--no-wrap", action="store_true", help="Disable wrapping (enabled by default)")
    args = ap.parse_args()
    
    cif_basename = Path(args.cif).stem
    fpdb = f"{cif_basename}.pdb"
    fmol2 = f"{cif_basename}_template.mol2"
    fbox = f"{cif_basename}.box"
    args.recenter = not args.no_recenter
    args.wrap = not args.no_wrap

    try:
        atoms = read(args.cif)
        print(f"[INFO] Successfully loaded with ASE")
    except Exception as e1:
        print(f"[ERROR] Failed to read CIF with ASE: {e1}", file=sys.stderr)
        try:
            s = Structure.from_file(args.cif)
            atoms = AseAtomsAdaptor.get_atoms(s)
            print(f"[INFO] Loaded with pymatgen")
        except Exception as e2:
            print(f"[ERROR] Failed to read CIF with pymatgen: {e2}", file=sys.stderr)
            sys.exit(1)
        raise Exception("[ERROR] Could not load CIF file with either ASE or pymatgen")

    # Make supercell if needed
    nx, ny, nz = args.supercell
    if (nx, ny, nz) != (1,1,1):
        from ase.build import make_supercell
        S = np.diag([nx, ny, nz])
        atoms = make_supercell(atoms, S)
        print(f"[INFO] Created {nx}x{ny}x{nz} supercell: {len(atoms)} atoms")

    # Identify molecules
    comps = split_molecules_pbc(atoms, scale=args.bond_scale)
    print(f"[INFO] Detected {len(comps)} molecules")
    
    if len(comps) == 1:
        print("[WARN] Detected a single connected component. This may not be a molecular crystal.")

    # Deterministic molecule ordering by fractional COM
    spos = atoms.get_scaled_positions()
    cell = atoms.get_cell()
    def frac_com(idxs):
        f = np.mean(spos[idxs], axis=0)
        return np.mod(f, 1.0)
    order_mols = sorted(range(len(comps)), key=lambda i: tuple(frac_com(comps[i])))
    comps = [comps[i] for i in order_mols]

    # Unwrap each molecule
    unwrapped_positions = []
    all_numbers = atoms.numbers.copy()
    for idxs in comps:
        pos = unwrap_to_single_image(atoms, idxs)
        unwrapped_positions.append(pos)

    # Optional: Recenter and wrap
    if args.recenter:
        print("[INFO] Recentering system to form a compact cluster...")
        unwrapped_positions = recenter_system(unwrapped_positions, np.array(atoms.get_cell()))
    
    if args.wrap:
        print("[INFO] Wrapping molecules back into the simulation box...")
        unwrapped_positions = wrap_to_box(unwrapped_positions, np.array(atoms.get_cell()))

    # Build template order for molecule 0
    idxs0 = comps[0]
    mol0 = Atoms(numbers=all_numbers[idxs0], positions=unwrapped_positions[0])
    G0 = build_graph(mol0, scale=args.bond_scale)
    template_local_order = deterministic_template_order(G0, mol0, list(range(len(idxs0))))
    print(f"[INFO] Template molecule has {len(idxs0)} atoms")

    # Prepare per-molecule reorder maps
    per_mol_orders: Dict[int, List[int]] = {}
    per_mol_orders[0] = template_local_order
    # For other molecules: find isomorphism mapping to template
    for mi in range(1, len(comps)):
        idxs_i = comps[mi]
        mol_i = Atoms(numbers=all_numbers[idxs_i], positions=unwrapped_positions[mi])
        mapping = best_isomorphism(mol_i, mol0, list(range(len(idxs_i))), 
                                   list(range(len(idxs0))), scale=args.bond_scale)
        inv = {v:k for k,v in mapping.items()}
        order_src_local = [inv[j] for j in template_local_order]
        per_mol_orders[mi] = order_src_local

    # Write PDB supercell
    write_pdb_supercell(fpdb, atoms, comps, per_mol_orders, unwrapped_positions, resname=args.resname)
    print(f"[OK] Wrote supercell PDB: {fpdb}")

    # Write mol2 for template molecule (for CGenFF)
    write_mol2_single_molecule(fmol2, atoms, idxs0, template_local_order,
                               unwrapped_positions[0], bond_scale=args.bond_scale,
                               mol_name=args.mol_name)
    print(f"[OK] Wrote template molecule mol2: {fmol2}")
    print(f"[INFO] Use this mol2 file with antechamber/parmchk2 for GAFF2 parameterization")
    
    # Write box parameters file
    write_box_file(fbox, atoms)
    print(f"[OK] Wrote box parameters: {fbox}")

if __name__ == "__main__":
    main()