#!/usr/bin/env python3
"""
Convert DCD trajectory frames to XYZ format.

This module provides functionality to extract frames from DCD trajectory files
and save them as XYZ files for use with quantum chemistry codes like DFTB+.
"""

import mdtraj as md
import numpy as np
from pathlib import Path
from typing import Union, Optional


def write_xyz(filename: Union[str, Path], topology: md.Topology, coordinates_nm: np.ndarray) -> None:
    """Write XYZ file with simple element symbols (no atom type distinction).
    
    Parameters
    ----------
    filename : str or Path
        Output XYZ file path.
    topology : md.Topology
        MDTraj topology object.
    coordinates_nm : np.ndarray
        Coordinates in nm (will be converted to Angstrom).
    """
    # Convert nm to Angstrom
    coords_ang = coordinates_nm * 10.0
    
    n_atoms = coords_ang.shape[0]
    
    with open(filename, 'w') as f:
        f.write(f"{n_atoms}\n")
        f.write("Generated by dcd2xyz.py\n")
        
        for i, atom in enumerate(topology.atoms):
            # Use element symbol only (C, H, N, etc.), not atom name (C1, H2, etc.)
            element = atom.element.symbol
            x, y, z = coords_ang[i]
            f.write(f"{element:2s} {x:15.8f} {y:15.8f} {z:15.8f}\n")


def convert_dcd_to_xyz(
    trajectory_file: Union[str, Path],
    topology_file: Union[str, Path],
    output_file: Union[str, Path],
    frame: int = 0,
    verbose: bool = True
) -> None:
    """Convert a DCD trajectory frame to XYZ format.
    
    Parameters
    ----------
    trajectory_file : str or Path
        Path to the DCD trajectory file.
    topology_file : str or Path
        Path to the topology file (PDB, etc.).
    output_file : str or Path
        Path to the output XYZ file.
    frame : int, optional
        Frame index to extract (default: 0, the first frame).
        Use -1 for the last frame, -2 for second to last, etc.
    verbose : bool, optional
        If True, print progress information (default: True).
    
    Raises
    ------
    ValueError
        If the frame index is out of range.
    FileNotFoundError
        If trajectory or topology files are not found.
    """
    # Load trajectory
    if verbose:
        print(f"Loading: {trajectory_file}")
    
    traj = md.load(str(trajectory_file), top=str(topology_file))
    
    if verbose:
        print(f"  Frames: {traj.n_frames}")
        print(f"  Atoms: {traj.n_atoms}")
    
    # Validate frame index
    if abs(frame) >= traj.n_frames:
        raise ValueError(
            f"Frame index {frame} is out of range for trajectory with {traj.n_frames} frames"
        )
    
    # Extract specified frame
    selected_frame = traj[frame]
    actual_frame = frame if frame >= 0 else traj.n_frames + frame
    
    if verbose:
        print(f"  Extracting frame: {actual_frame}")
    
    # Save as XYZ with simple element symbols
    write_xyz(output_file, selected_frame.topology, selected_frame.xyz[0])
    
    if verbose:
        print(f"\nSaved frame {actual_frame}: {output_file}")
        print(f"\nAtoms in structure:")
        for atom in selected_frame.topology.atoms:
            print(f"  {atom.index}: {atom.element.symbol} ({atom.name})")


def main():
    """Command-line interface for dcd2xyz conversion."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Extract frames from DCD trajectory and save as XYZ files."
    )
    parser.add_argument(
        "-t", "--trajectory",
        default="mol1.dcd",
        help="DCD trajectory file (default: mol1.dcd)"
    )
    parser.add_argument(
        "-p", "--topology",
        default="mol1.pdb",
        help="Topology file (default: mol1.pdb)"
    )
    parser.add_argument(
        "-o", "--output",
        default="mol1.xyz",
        help="Output XYZ file (default: mol1.xyz)"
    )
    parser.add_argument(
        "-f", "--frame",
        type=int,
        default=0,
        help="Frame index to extract (default: 0). Use -1 for last frame."
    )
    parser.add_argument(
        "-q", "--quiet",
        action="store_true",
        help="Suppress output messages"
    )
    
    args = parser.parse_args()
    
    convert_dcd_to_xyz(
        trajectory_file=args.trajectory,
        topology_file=args.topology,
        output_file=args.output,
        frame=args.frame,
        verbose=not args.quiet
    )


if __name__ == "__main__":
    main()
