# MD Settings Configuration File

# MD parameters
md:
  timestep: 0.0005          # ps (0.5 fs)
  traj_frequency: 4       # steps
  nvt:
    temperature: 300.0       # K
    coupling_frequency: 1.0  # ps
  npt:
    pressure: 1              # bar
    barostat_frequency: 25   # steps
  simulation_time: 0.1       # ps

# Output settings
output:
  directory: "output"
